CREATE TABLE IF NOT EXISTS fee_policy (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pg_company VARCHAR(50) NOT NULL,
    merchant_id VARCHAR(100) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    fee_type VARCHAR(20) NOT NULL,
    fee_value DECIMAL(18, 6) NOT NULL,
    settlement_cycle_days INT NOT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_fee_policy_lookup
    ON fee_policy(pg_company, merchant_id, payment_method, start_date, end_date);

CREATE TABLE IF NOT EXISTS payment_transaction (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id VARCHAR(100) NOT NULL,
    pg_company VARCHAR(50) NOT NULL,
    merchant_id VARCHAR(100) NOT NULL,
    payment_method VARCHAR(50) NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    amount DECIMAL(18, 0) NOT NULL,
    transaction_date DATE NOT NULL,
    original_transaction_id VARCHAR(100),
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_payment_transaction_id UNIQUE (transaction_id)
);

CREATE INDEX IF NOT EXISTS idx_tx_pg_date ON payment_transaction(pg_company, transaction_date);
CREATE INDEX IF NOT EXISTS idx_tx_merchant_date ON payment_transaction(merchant_id, transaction_date);
CREATE INDEX IF NOT EXISTS idx_tx_original_tx ON payment_transaction(original_transaction_id);

CREATE TABLE IF NOT EXISTS settlement_expected (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    base_date DATE NOT NULL,
    pg_company VARCHAR(50) NOT NULL,
    transaction_id VARCHAR(100) NOT NULL,
    merchant_id VARCHAR(100) NOT NULL,
    transaction_date DATE NOT NULL,
    transaction_type VARCHAR(20) NOT NULL,
    amount DECIMAL(18, 0) NOT NULL,
    fee_amount DECIMAL(18, 0) NOT NULL,
    vat_amount DECIMAL(18, 0) NOT NULL,
    expected_settlement_amount DECIMAL(18, 0) NOT NULL,
    expected_settlement_date DATE NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_settlement_base_pg_tx UNIQUE (base_date, pg_company, transaction_id)
);

CREATE INDEX IF NOT EXISTS idx_settlement_merchant_date
    ON settlement_expected(merchant_id, transaction_date);
CREATE INDEX IF NOT EXISTS idx_settlement_transaction_date
    ON settlement_expected(transaction_date);
CREATE INDEX IF NOT EXISTS idx_settlement_base_pg
    ON settlement_expected(base_date, pg_company);
